number:
  per_page: 10
  short_miximum: 5
  user_per_page: 15
  count: 5
  round: 2
admin:
  books:
    picture_height: 220
    picture_width: 150
    picture_height300: 420
    picture_width300: 280
    picture_default: "bookdefault2.jpg"
    picture_default_2: "bookdefault2.jpg"
    max_string: 10
    pages: 12
    max_rate: 5
    max_number_page: 50000
    min_number_page: 1
    min_title_length: 6
roles:
  - user
  - admin
user:
  gravantar_size230: 230
  gravantar_size150: 150
  max_string: 15
  pages: 12
  picutre_height330: 330
  picture_width250: 250
favorites:
  create: "create"
  destroy: "destroy"
books:
  picutre_height330: 330
  picture_width250: 250
  mg-left: 100px
review:
  picture_size50: 50
favorite:
  books:
    pages: 6
    suggest_un_favorite_books: 5
